---
title: "Tufte Handout"
subtitle: "W4 In-class Participation"
author: "Sihao Miao"
date: "`r Sys.Date()`"
output:
  tufte::tufte_html: default
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: xelatex
bibliography: example.bib
link-citations: yes
---

```{r setup, include=FALSE}
library(tufte)
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(collapse = TRUE, warning = FALSE, message = FALSE, echo = FALSE, cache.comments = FALSE, cache.extra= list(cache.extra = list(
  R.version, sessionInfo(), format(Sys.Date(), '%Y-%m'))))
```

```yaml
---
title: "An Example Using the Tufte Style"
author: "Sihao Miao"
output:
  tufte::tufte_handout: default
  tufte::tufte_html: default
---
```

```{r}
library(tidyverse)
```

Using external code in Rmd with source().
```{r RunCodeChunkNoEval, eval=FALSE}
source('my-external-code.R')
```
```{r RunCodeChunk, results='hide'}
source('my-external-code.R')
```

```{r RunCodeChunkShowAll, echo=FALSE}
source('my-external-code.R')
```

Using external code in Rmd with knitr::read_chunk()
```{r}
knitr::read_chunk('my-external-code.R')
```

```{r set-up-the-data, eval=FALSE}

```

```{r set-up-and-print-the-data, echo=FALSE}
<<set-up-the-data>>
<<print-the-data>>
```

```{r plot-the-data,echo=FALSE}

```


```{r starwars-plot, fig.cap= "A ggplot of starwars stuff"}

starwars %>%
  filter(species =="Human")%>% ggplot()+aes(x=height, y=mass)+geom_point()
```

```{r starwars-tbl}
starwars %>%
  filter(species == "Human")%>%
  select(name, height, mass, homeworld)%>%
  knitr::kable(caption="A knitr kable table of starwars data")
```

We can see the article "Replication". [@kornberg1980replication]      

[@orgel1992molecular] says something about molecular replication.
  
# References cited
